language: python

notifications:
  email:
    on_success: never

branches:
  only:
  - master

python:
  - "2.7"

  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"

# command to install dependencies
install:
  # install lib in develop mode
  - pip install -e .[tests]

  - pip install -r requirements.txt

  - pip install codecov

# command to run tests
script:
  - coverage run --source=solarsystem -m pytest -v

after_success:
  - codecov
