language: python

notifications:
  email:
    on_success: never

python:
  - "3.0"
  - "3.1"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"      
  - "3.7"
  - "3.8"
  - "nightly"

  # PyPy versions
  - "pypy3" 

# command to install dependencies
install:
  # install lib in develop mode
  - pip install -e .[tests]

  - pip install -r requirements.txt

# command to run tests
script:
  - pytest
